[executor]
enable_auto_refund = true
[executor.retry]
initial_backoff_seconds = 1 # default 30
interval_seconds = 1 # default 30
scaling_factor = 1 # default 1

# [server] # optional
# enable = true # default false
# port = 24242

[[service]] # a service represents a set of contracts and an account
# id = "my-service" # optional if only one service is configured
signer_keystore = "/Users/end-of-master/EndOfMaster/celer-message-bus-demo/config/keystore.json"
signer_passphrase = "dfwork1015"  #password
[[service.contracts]]
chain_id = 5
address = "0x450F9F7De6FC5F1Edc5A7cBeA6549Fd124977ccb" # this contract address is used to query messages from SGN
[[service.contracts]]
chain_id = 97
address = "0xD3690FF87908907a3Bc6638bb73b0E8c905A7c7F"

[sgnd]
sgn_grpc = "cbridge-v2-test.celer.network:9094"
gateway_grpc = "cbridge-v2-test.celer.network:9094"

[db]
url = "localhost:26257"

# [alert]
# type = "slack" # only slack is supported for now
# webhook = "<slack-web-hook-url>"
# [[alert.low_gas_thresholds]]
# chain_id = 5
# threshold = "2000000000000000000"
# [[alert.low_gas_thresholds]]
# chain_id = 97
# threshold = "1000000000000000000"